version: "3.1"

services:
  lobo-liquibase:
    container_name: lobo-liquibase
    image: liquibase/liquibase

    command: --url=jdbc:postgresql://lobo-db:5432/bookstore?user=postgres&password=1234 --changeLogFile="db.changelog-master.xml" update

    volumes:
      - ./db/changelog:/liquibase/changelog

    networks:
      lobo-net:
        ipv4_address: 170.17.0.152


networks:
  lobo-net:    
    driver: bridge    
    ipam:
      config:
        - subnet: "170.17.0.0/24"

